spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

#zuul默认开启负载均衡。重试默认不开启，需手动开启，需要添加spring-retry依赖
zuul:
  retryable: true
  routes:
    item-service: /item-service/**  
    user-service: /user-service/**
    order-service: /order-service/**
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      